backend:
  name: git-gateway

media_folder: source/assets/img/uploads
public_folder: /assets/img/uploads

publish_mode: editorial_workflow

site_url: https://thomas.codes
display_url: https://thomas.codes

collections:
#markdown middleman blog example
  - name: articles
    label: Article
    folder: source/articles/
    extension: .html.md.erb
    format: frontmatter
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{title}}'
    fields:
      - {label: Title, name: title, widget: string, required: true}
      - {label: Date, name: date, widget: date, format: "YYYY/MM/DD"}
      - {label: Published, name: published, widget: boolean, default: true, required: false}
      - {label: Background Color, name: background_color, widget: string, required: false}
      - {
          label: Category,
          name: category, 
          widget: list,
          allow_add: true
        }
      - {label: Blurb, name: blurb, widget: text, required: true}
      - {label: Body, name: body, widget: markdown}
      - { 
          label: Newsletter,
          name: newsletter,
          widget: object,
          fields: [
            { 
              label: Headline,
              name: headline,
              widget: string,
              default: "There's more to come",
            },
            { 
              label: Body,
              name: body,
              widget: markdown,
              default: "I'm dusting my blog off and making a point to start sharing what I know again. <b>Subscribe and follow along!</b>",
            },
          ],
        }

  - name: talks
    label: Talk
    folder: source/talks/
    extension: .html.md.erb
    format: frontmatter
    create: true
    slug: '{{title}}'
    fields:
      - {label: layout, name: layout, widget: hidden, default: "talk" }
      - {label: Title, name: title, widget: string, required: true}
      - {label: Date, name: date, widget: date, format: "YYYY/MM/DD"}
      - {label: Published, name: published, widget: boolean, default: true, required: false}
      - {label: Video, name: video, widget: string}
      - {label: Where, name: where, widget: string }
      - {label: Body, name: body, widget: markdown}

  - name: categories
    label: Category
    folder: source/categories/
    extension: .html.md.erb
    format: frontmatter
    create: true
    slug: '{{code}}'
    identifier_field: code
    fields:
      - {label: Name, name: name, widget: string, required: true}
      - {label: Code, name: code, widget: string, required: true}
      - {label: Body, name: body, widget: markdown, required: false}

  - name: settings
    label: Settings
    files:
      - file: data/settings/site.yml
        label: Site
        name: site
        fields:
          - label: About
            name: about
            widget: text
