backend:
  name: git-gateway

media_folder: source/images/uploads
public_folder: /images/uploads

publish_mode: editorial_workflow

collections:
#markdown middleman blog example
  - name: articles
    label: Article
    folder: source/articles/
    extension: .html.md
    format: frontmatter
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{title}}'
    fields:
      - {label: Title, name: title, widget: string, required: true}
      - {label: Date, name: date, widget: date, format: "YYYY/MM/DD"}
      - {label: Published, name: published, widget: boolean, default: true}
      - {
          label: Category,
          name: category, 
          widget: list,
          allow_add: true
        }
      - {label: Body, name: body, widget: markdown}
      - { 
          label: Newsletter,
          name: newsletter,
          widget: object,
          fields: [
            { 
              label: Headline,
              name: headline,
              widget: string,
              default: "There's more to come",
            },
            { 
              label: Body,
              name: body,
              widget: markdown,
              default: "I'm dusting my blog off and making a point to start sharing what I know again. <b>Subscribe and follow along!</b>",
            },
          ],
        }

  - name: categories
    label: Category
    folder: source/categories/
    extension: .html.md
    format: frontmatter
    create: true
    slug: '{{code}}'
    identifier_field: code
    fields:
      - {label: Name, name: name, widget: string, required: true}
      - {label: Code, name: code, widget: string, required: true}
      - {label: Body, name: body, widget: markdown, required: false}
